# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 03:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_number', models.CharField(help_text='Enter Part Number', max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text="Enter Part's Description", max_length=100)),
                ('supplier_name', models.CharField(help_text="Enter Supplier's Name", max_length=50)),
                ('eta_dicv', models.CharField(help_text='Enter ETA', max_length=30)),
                ('truck_details', models.CharField(help_text='Enter Truck Details', max_length=30)),
                ('shortage_reason', models.CharField(help_text='Enter Reason For Shortage', max_length=100)),
                ('delayed', models.BooleanField(default=False, help_text='Check if the part is delayed')),
            ],
            options={
                'ordering': ['-part_number'],
            },
        ),
    ]
