# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-18 10:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critical_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='backlog',
            field=models.CharField(default=0, help_text='Enter Backlog', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='count',
            field=models.IntegerField(default=0, help_text='Enter count'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='p_q',
            field=models.CharField(default=0, help_text='Enter P Q', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='planned_vehicle_qty',
            field=models.CharField(default=0, help_text='Enter planned vehicle quantity', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='pmc',
            field=models.CharField(default=0, help_text='Enter PMC', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='quantity',
            field=models.IntegerField(default=0, help_text='Enter Quantity Avl DICV'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='quantity_expected',
            field=models.CharField(default=0, help_text='Enter quantity expected', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='region',
            field=models.CharField(default=0, help_text='Enter Region', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='reported_on',
            field=models.DateField(default=datetime.datetime.now, help_text='Reported on', max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='shop',
            field=models.CharField(default=0, help_text='Enter Text', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='short_on',
            field=models.DateField(default=datetime.datetime.now, help_text='Short on', max_length=30),
        ),
        migrations.AddField(
            model_name='part',
            name='team',
            field=models.CharField(default=0, help_text='Enter Team', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='unloading_point',
            field=models.CharField(default=0, help_text='Enter Unloading Point', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='part',
            name='variants',
            field=models.CharField(default=0, help_text='Enter Variants', max_length=30),
            preserve_default=False,
        ),
    ]
