# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='planned_vehicle_qty',
            field=models.IntegerField(help_text='Enter planned vehicle quantity'),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity_expected',
            field=models.IntegerField(help_text='Enter quantity expected'),
        ),
    ]
