# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0002_auto_20171031_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='shop',
            field=models.CharField(
                choices=[('MDT ENGINE', 'MDT ENGINE'), ('HDT ENGINE', 'HDT ENGINE'), ('TRANSMISSION', 'TRANSMISSION'),
                         ('CASTING AND FORGING', 'CASTING AND FORGING')], help_text='Enter Text', max_length=30),
        ),
    ]
