# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-03 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0003_auto_20171031_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='part',
            name='delayed',
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.CharField(blank=True, choices=[('Critical', 'Critical'), ('Warning', 'Warning')],
                                   help_text='Select the part Status', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='shop',
            field=models.CharField(
                choices=[('MDT ENGINE', 'MDT ENGINE'), ('HDT ENGINE', 'HDT ENGINE'), ('TRANSMISSION', 'TRANSMISSION'),
                         ('CASTING AND FORGING', 'CASTING AND FORGING'), ('AXLE', 'AXLE')], help_text='Enter Text',
                max_length=30),
        ),
    ]
