# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0005_auto_20171112_0910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.IntegerField(choices=[(1, 'Normal'), (2, 'Warning'), (3, 'Critical')], default=1,
                                      help_text='Select the part Status'),
        ),
    ]
