# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('critical_list', '0007_auto_20171113_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='count',
            field=models.CharField(help_text=b'Enter count', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='planned_vehicle_qty',
            field=models.CharField(help_text=b'Enter planned vehicle quantity', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity',
            field=models.CharField(help_text=b'Enter Quantity Avl DICV', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='quantity_expected',
            field=models.CharField(help_text=b'Enter quantity expected', max_length=50),
        ),
        migrations.AlterField(
            model_name='part',
            name='status',
            field=models.CharField(choices=[(1, b'Normal'), (2, b'Warning'), (3, b'Critical')], default=1, help_text=b'Select the part Status', max_length=50),
        ),
    ]
