# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0010_auto_20171121_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='pmc',
            field=models.CharField(
                choices=[('MDT ENGINE', 'MDT ENGINE'), ('HDT ENGINE', 'HDT ENGINE'), ('TRANSMISSION', 'TRANSMISSION'),
                         ('CASTING AND FORGING', 'CASTING AND FORGING'), ('AXLE', 'AXLE')], help_text='Enter PMC',
                max_length=20),
        ),
        migrations.AlterField(
            model_name='part',
            name='shop',
            field=models.CharField(help_text='Enter Text', max_length=30),
        ),
    ]
