# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 12:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0012_auto_20171129_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='p_q',
            field=models.BooleanField(default=False, help_text='Enter P Q'),
        ),
        migrations.AlterField(
            model_name='part',
            name='region',
            field=models.CharField(
                choices=[('Import', 'Import'), ('Chennai', 'Chennai'), ('North', 'North'), ('South', 'South'),
                         ('West', 'West'), ('East', 'East')], help_text='Enter Region', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='team',
            field=models.CharField(
                choices=[('Import', 'Import'), ('PTI', 'PTI'), ('Bus', 'Bus'), ('Vehicle', 'Vehicle')],
                help_text='Enter Team', max_length=10),
        ),
        migrations.AlterField(
            model_name='part',
            name='unloading_point',
            field=models.CharField(choices=[('LC', 'LC'), ('DOL', 'DOL'), ('FS', 'FS'), ('Chennai', 'Chennai')],
                                   help_text='Enter Unloading Point', max_length=10),
        ),
    ]
