# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0013_auto_20171129_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='p_q',
            field=models.CharField(choices=[('Y', 'Y'), ('N', 'N')], default='N', help_text='Enter P Q', max_length=1),
        ),
    ]
