# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0014_auto_20171129_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='shortage_reason',
            field=models.CharField(blank=True, help_text='Enter Reason For Shortage', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='part',
            name='truck_details',
            field=models.CharField(blank=True, help_text='Enter Truck Details', max_length=30, null=True),
        ),
    ]
