# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0015_auto_20171129_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='eta_dicv',
            field=models.CharField(help_text='Enter ETA', max_length=50),
        ),
    ]
