# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0016_auto_20171129_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='thread_status',
            field=models.IntegerField(choices=[(True, 'Open'), (False, 'Closed')], default=True,
                                      help_text='Select the thread Status'),
        ),
    ]
