# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-14 02:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0017_part_thread_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='thread_status',
            field=models.BooleanField(choices=[(True, 'Open'), (False, 'Closed')], default=True,
                                      help_text='Select the thread Status'),
        ),
    ]
