# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Part',
            fields=[
                ('part_number', models.CharField(help_text='Enter Part Number', max_length=30, primary_key=True, serialize=False)),
                ('description', models.CharField(help_text="Enter Part's Description", max_length=100)),
                ('supplier_name', models.EmailField(help_text="Enter Supplier's Name", max_length=50)),
                ('eta', models.CharField(help_text='Enter ETA', max_length=30)),
                ('dicv', models.CharField(max_length=30)),
                ('truck', models.CharField(help_text='Choose Truck Number', max_length=30)),
                ('details', models.CharField(help_text='Enter Details', max_length=100)),
                ('shortage_reason', models.CharField(help_text='Enter Reason For Shortage', max_length=100)),
            ],
            options={
                'ordering': ['-part_number'],
            },
        ),
    ]
