# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='part',
            old_name='eta',
            new_name='eta_dicv',
        ),
        migrations.RemoveField(
            model_name='part',
            name='details',
        ),
        migrations.RemoveField(
            model_name='part',
            name='dicv',
        ),
        migrations.RemoveField(
            model_name='part',
            name='truck',
        ),
        migrations.AddField(
            model_name='part',
            name='truck_details',
            field=models.CharField(default=1, help_text='Enter Truck Details', max_length=30),
            preserve_default=False,
        ),
    ]
