# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0002_auto_20171016_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='delayed',
            field=models.BooleanField(default=False, help_text='Check if the part is delayed'),
        ),
    ]
