# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0003_part_delayed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='part',
            name='supplier_name',
            field=models.CharField(help_text="Enter Supplier's Name", max_length=50),
        ),
    ]
