# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sos',
            fields=[
                ('date', models.DateField(default=datetime.datetime.now, help_text='Date', max_length=30)),
                ('id', models.CharField(help_text='Id', max_length=30, primary_key='True', serialize=False)),
                ('uid', models.CharField(help_text='Uid', max_length=30)),
                ('name', models.CharField(help_text='Name', max_length=50)),
                ('level', models.IntegerField(help_text='Enter Level')),
                ('content', models.CharField(help_text='Enter Content', max_length=100)),
                ('media', models.CharField(help_text='Media', max_length=20)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
