# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-10 11:33
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-posted_by']},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='uid',
        ),
        migrations.AddField(
            model_name='comment',
            name='posted_by',
            field=models.ForeignKey(default=1, help_text='Original Poster', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='comment_by', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sos',
            name='posted_by',
            field=models.ForeignKey(help_text='Original Poster', on_delete=django.db.models.deletion.CASCADE,
                                    related_name='post_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
