# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='media',
            field=models.FileField(blank=True, help_text='Media', upload_to='comment/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='sos',
            name='media',
            field=models.FileField(blank=True, help_text='Media', upload_to='content/%Y/%m/%d/'),
        ),
    ]
