# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 10:19
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sos', '0002_auto_20171105_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Enter Level'),
        ),
        migrations.AlterField(
            model_name='sos',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='Date', max_length=30),
        ),
    ]
