# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:03
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('critical_list', '0007_auto_20171113_0902'),
        ('sos', '0004_auto_20171117_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='partid',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE,
                                    to='critical_list.Part'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='sosid',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='sos.Sos'),
        ),
    ]
