# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 15:05
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sos', '0005_auto_20171118_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='partid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE,
                                    to='critical_list.Part'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='sosid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sos.Sos'),
        ),
    ]
