# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-12 16:41
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sos', '0007_comment_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sos',
            name='posted_by',
        ),
        migrations.RemoveField(
            model_name='sos',
            name='users',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='sosid',
        ),
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.BooleanField(default=False, help_text='Part or Notification'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='partid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='critical_list.Part'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Sos',
        ),
    ]
