# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-11 13:03
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('sos', '0008_auto_20171212_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now, help_text='posted at'),
        ),
    ]
